### PR TITLE
Fetch list of repositories by topic

### LINKED ISSUE #48: Fetch list of repositories with GraphQL API
The [script](https://github.com/ExpediaGroup/expediagroup.github.io/blob/main/src/scripts/build-repo-data.js) that queries repositories info with GitHub GraphQL API is currently based on an hardcoded list of repositories.

Instead of being hardcoded, this starting list of repositories could be fetched with the GraphQL API, in turn. We can prepare a query that starts from the GitHub organization and gets its repositories.

To decide which repositories should be shown in the Home Page (i.e. the "featured" repositories) and which ones should be shown in the Repositories Page, we could use GitHub topics: for example a topic `is-featured` and a topic `is-listed`, or similar. This way, when you want to change the repositories that are shown in the website you don't need to update a JS file, you just update the repo's topics and rebuild the site.

### PR DESCRIPTION
**Pull request by ffeltrinelli**
### :pencil: Description

Fetch the list of repositories with GitHub GraphQL API instead of being hardcoded. The search is done within the `ExpediaGroup` organization by `topic`:

- if the repo has topic `oss-portal-listed` it will be shown in the Repositories Page
- if the repo has topic `oss-portal-featured` it will be shown in the Repositories Page and in the Home Page

This improves because:

* to change the repositories shown in the portal you just need to add/remove a GitHub topic on the repo, instead of committing on an hardcoded list. Then you have to trigger a portal rebuild, or just wait for the daily build to be automatically triggered.
* Previously the build made N calls to GitHub API (where N = number of repos), now it only makes 2 calls (one for the featured repos and one for the listed repos)

### :framed_picture: Screenshot

Example of repo with the `oss-portal-featured` topic: 

### :link: Related Issues
Fixes #48

### CODE REVIEW

**Comment by ffeltrinelli** [comment]
@nikos912000 @worldtiki let me know what you think about this :-) I've already added the correct topics to all the repositories that are currently shown in the portal (so that after this pull request the portal shows exactly the same repos).

**Comment by worldtiki** [comment]
I think this is creating rules that are hidden and undocumented.
I'd rather just display repos based on popularity or activity and use labels to hide the ones that we (for whatever reason) don't want to dispplay

**Comment by ffeltrinelli** [comment]
I think this pull request's rule is quite straightforward: add a topic --> show a repo. And it gives full control to what is shown. I've documented it.

I also was a supporter of the approach you mention of finding out rules for popularity or activity, because it seems to be something that automatically evolves in the future. But would it really be like that, seamlessly? And do we really need it? The rules would be more complex and there could be exceptions difficult to handle (the block list driven by topics that you mention is a first example of that).

**Comment by worldtiki** [comment]
Those are good points. Approved

**Review by worldtiki — APPROVED** [review]

**Comment by nikos912000** [comment]
I like the idea of showing repos based on a predefined topic 👍

**Review by nikos912000 — APPROVED** [review]

**Pull request merged**
