### PR TITLE
🐞 fix: removed package-lock.json file and added in gitignore

### PR DESCRIPTION
**Pull request by YashCerebulb**
### :pencil: Description

🐞 fix: removed package-lock.json file and added in .gitignore
> we should avoid `package-lock.json` to be pushed in our repository.

### CODE REVIEW

**Comment by worldtiki** [comment]
Isn't it best practice to commit the package lock file?

```
It is highly recommended you commit the generated package lock to source control: this will allow anyone else on your team, your deployments, your CI/continuous integration, and anyone else who runs npm install in your package source to get the exact same dependency tree that you were developing on. Additionally, the diffs from these changes are human-readable and will inform you of any changes npm has made to your node_modules, so you can notice if any transitive dependencies were updated, hoisted, etc.
```
From https://docs.npmjs.com/cli/v6/configuring-npm/package-locks

**Comment by YashCerebulb** [comment]
> Isn't it best practice to commit the package lock file?
> 
> ```
> It is highly recommended you commit the generated package lock to source control: this will allow anyone else on your team, your deployments, your CI/continuous integration, and anyone else who runs npm install in your package source to get the exact same dependency tree that you were developing on. Additionally, the diffs from these changes are human-readable and will inform you of any changes npm has made to your node_modules, so you can notice if any transitive dependencies were updated, hoisted, etc.
> ```
> 
> From https://docs.npmjs.com/cli/v6/configuring-npm/package-locks

Hi @worldtiki,
     sorry, I didn't noticed that we are not using `yarn` here. my intent was to not mixing up package manager like `npm` and `yarn`.

**Comment by ffeltrinelli** [comment]
> Hi @worldtiki, sorry, I didn't noticed that we are not using `yarn` here. my intent was to not mixing up package manager like `npm` and `yarn`.

Hi @YashCerebulb , thanks for your explanation, based on your reply I'm closing the pull request.

**Comment by worldtiki** [comment]
@ffeltrinelli, @YashCerebulb  I'm not an expert in npm/yarn :s
Maybe we should confirm this.

**Comment by YashCerebulb** [comment]
Hi @worldtiki @ffeltrinelli ,
as we are using only `npm` here. It is good to have `package-lock.json` in our repo. Based on [this](https://nodejs.dev/learn/the-package-lock-json-file) article.
It's not required if we are using `yarn` because it's already have `yarn.lock` file which help us to sync packages across multiple systems.

**Pull request closed without merging**
